# -*- encoding: utf-8 -*-

{
    "name": "Connect",
    "version": "2.0.2",
    "author": "Oduist",
    "maintainer": "Oduist",
    "live_test_url": "https://connect-demo.oduist.com/",
    "price": 0, # TRIAL
    "currency": "EUR",
    "support": "support@oduist.com",
    "license": "Other proprietary",
    "category": "Phone",
    "summary": "Twilio and Odoo integration application",
    "description": "",
    "depends": ["mail", "contacts", "sms", "resource"],
    "external_dependencies": {
        "python": ["twilio", "openai", "PyJWT"],
    },
    "sequences": True,
    "data": [
        "data/res_users.xml",
        "data/license.xml",
        "data/ir_cron.xml",
        "data/twiml.xml",
        "data/res_partner.xml",
        "data/whatsapp_templates.xml",
        # Security
        "security/groups.xml",
        "security/admin.xml",
        "security/webhook.xml",
        "security/user.xml",
        "security/license.xml",
        "security/user_record_rules.xml",
        "security/admin_record_rules.xml",
        # Views
        "views/menu.xml",
        "views/settings.xml",
        "views/license.xml",
        "views/domain.xml",
        "views/user.xml",
        "views/twiml.xml",
        "views/debug.xml",
        "views/exten.xml",
        "views/call.xml",
        "views/callflow.xml",
        "views/channel.xml",
        "views/outgoing_callerid.xml",
        "views/pbx_group.xml",
        "views/recording.xml",
        "views/number.xml",
        "views/favorite.xml",
        "views/res_partner.xml",
        "views/message.xml",
        "views/message_configuration.xml",
        "views/message_content_template.xml",
        "views/whatsapp_sender.xml",
        "views/documentation.xml",
        # Wizard
        "wizard/transfer.xml",
        "wizard/sms_composer_views.xml",
        "wizard/whatsapp_composer_views.xml",
        "wizard/originate_to_wizard_views.xml",
    ],
    "demo": [],
    "installable": True,
    "application": True,
    "auto_install": False,
    "images": ["static/description/logo.png"],
    "assets": {
        "web.assets_backend": [
            "/connect/static/src/icomoon/style.css",
            # "/connect/static/src/components/phone/*/*",
            "/connect/static/src/components/license_banner/*",
            # "/connect/static/src/js/main.js",
            # "/connect/static/src/js/utils.js",
            "/connect/static/src/widgets/phone_field/*",
            "/connect/static/src/services/actions/*",
            # "/connect/static/src/services/active_calls/*",
            # "/connect/static/src/services/mail/*",
            "/connect/static/src/core/common/*",
        ],
        "web.assets_qweb": [
            "connect/static/src/components/license_banner/*.xml",
        ],
    },
    "post_init_hook": "post_init_hook",
}
