from . import call
from . import callflow
from . import ir_module_module
from . import channel
from . import debug
from . import domain
from . import exten
from . import favorite
from . import license
from . import mail
from . import message
from . import message_configuration
from . import number
from . import outgoing_callerid
from . import recording
from . import res_partner
from . import res_users
from . import settings
from . import sms_sms
from . import twiml
from . import user
from . import documentation
from . import whatsapp_sender
from . import message_content_template
