# -*- encoding: utf-8 -*-
{
    "name": "Twilio BYOC",
    "version": "1.0.2",
    "author": "Oduist",
    "price": 499,
    "currency": "EUR",
    "maintainer": "Oduist",
    "live_test_url": "https://connect-demo-18.oduist.com/",
    "support": "support@oduist.com",
    "license": "Other proprietary",
    "category": "Phone",
    "summary": "Twilio Bring Your Own Carrier",
    "description": "Twilio BYOC is a feature that allows you to use your own carrier to make and receive calls.",
    "depends": ["connect"],
    "data": [
        "security/user.xml",
        "security/admin.xml",
        "views/byoc.xml",
        "views/domain.xml",
        "views/number.xml",
        "views/outgoing_rule.xml",
        "data/outgoing_rules.xml",
    ],
    "demo": [],
    "qweb": ["static/src/xml/*.xml"],
    "installable": True,
    "application": False,
    "auto_install": False,
    "images": ["static/description/logo.png"],
}
