name: CI
on:
  push:
    branches:
      - 16.0
      - 17.0
      - 18.0

jobs:
  Install:
    runs-on: ubuntu-22.04
    container:
      image: odoo:${{ github.ref_name }}
      options: --user=root
    services:
      db:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: odoo
          POSTGRES_USER: odoo
    steps:
      - name: Check out repository code
        uses: actions/checkout@master
      - name: Update
        run: apt update -y && apt install -y python3-openai
      - name: Install module requirements
        run: pip3 install twilio elevenlabs --break-system-packages
      - name: Install odoo modules
        run: >
          odoo --addons-path=$GITHUB_WORKSPACE --database=ephemeral
          --db_host=db --db_user=odoo --db_password=odoo
          --stop-after-init --no-http
          -i connect,connect_crm,connect_helpdesk,connect_elevenlabs
